/*
 * Copyright (c) 2012. Redex Scripting - Unauthorized use prohibited by author.
 */

package RedexFighter.gui;

/**
 * Created by IntelliJ IDEA.
 * User: Tim
 * Date: 6/19/12
 * Time: 3:47 PM
 * To change this template use File | Settings | File Templates.
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on Jun 19, 2012, 3:50:20 PM
 */

import RedexFighter.Store;

import javax.swing.*;
import java.util.ArrayList;

/**
 * @author Tim
 */
public class GUI extends javax.swing.JFrame {
    public static boolean guiRun = false;
    public static ArrayList<String> Names = new ArrayList<String>();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();

    }

    public  void setComboBox() {
        localNpc.setModel(new DefaultComboBoxModel(Names.toArray(new String[Names.size()])));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {


        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        npcList = new javax.swing.JList();
        localNpc = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        npcTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        radiusChk = new javax.swing.JCheckBox();
        radTxt = new javax.swing.JTextField();
        bankChk = new javax.swing.JCheckBox();
        B2PChk = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lootList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        lootTxt = new javax.swing.JTextField();
        addLoot = new javax.swing.JButton();
        alchChk = new javax.swing.JCheckBox();
        toAlchTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        alchList = new javax.swing.JList();
        addAlch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText(""); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jTabbedPane1.setName("RedexFighter Prefrences"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        npcList.setName("npcList"); // NOI18N
        jScrollPane1.setViewportView(npcList);

        localNpc.setName("localNpc"); // NOI18N

        jLabel1.setText("Enter a npc name or select from dropdown."); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        npcTxt.setText(""); // NOI18N
        npcTxt.setName("npcTxt"); // NOI18N

        addBtn.setText("Add"); // NOI18N
        addBtn.setName("addBtn"); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        radiusChk.setText("Stay within radius of: "); // NOI18N
        radiusChk.setName("radiusChk"); // NOI18N

        radTxt.setText(""); // NOI18N
        radTxt.setName("radTxt"); // NOI18N

        bankChk.setText("Banking"); // NOI18N
        bankChk.setName("bankChk"); // NOI18N

        B2PChk.setText("Bones to Peaches"); // NOI18N
        B2PChk.setName("B2PChk"); // NOI18N

        jLabel3.setText("Options"); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        startBtn.setText("Start"); // NOI18N
        startBtn.setName("startBtn"); // NOI18N
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(npcTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(localNpc, javax.swing.GroupLayout.Alignment.LEADING, 0, 163, Short.MAX_VALUE)))
                                                .addGap(55, 55, 55)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(B2PChk)
                                                        .addComponent(bankChk)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(radiusChk)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(radTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addComponent(jLabel3))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(204, 204, 204)
                                                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(radiusChk)
                                                                        .addComponent(radTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(bankChk)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(B2PChk))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(npcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(localNpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(addBtn)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(startBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Setup", jPanel1); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        lootList.setName("lootList"); // NOI18N
        jScrollPane2.setViewportView(lootList);

        jLabel4.setText("Enter a name for an item you would like to pickup"); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        lootTxt.setText(""); // NOI18N
        lootTxt.setName("lootTxt"); // NOI18N

        addLoot.setText("Add"); // NOI18N
        addLoot.setName("addLoot"); // NOI18N
        addLoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLootActionPerformed(evt);
            }
        });

        alchChk.setText("Alch Items"); // NOI18N
        alchChk.setName("alchChk"); // NOI18N
        alchChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alchChkActionPerformed(evt);
            }
        });

        toAlchTxt.setText(""); // NOI18N
        toAlchTxt.setName("toAlchTxt"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        alchList.setName("alchList"); // NOI18N
        jScrollPane3.setViewportView(alchList);

        addAlch.setText("Add"); // NOI18N
        addAlch.setName("addAlch"); // NOI18N
        addAlch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlchActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter a name or ID"); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(addLoot, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(toAlchTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                                        .addComponent(addAlch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE))
                                                .addGap(41, 41, 41))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(65, 65, 65)
                                                                .addComponent(lootTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel4)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(alchChk, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(52, 52, 52))))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lootTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(alchChk)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addLoot)
                                        .addComponent(toAlchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addAlch)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Looting", jPanel2); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jButton1.setText("Load Settings"); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save Settings"); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                .addContainerGap(493, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addContainerGap(266, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Options", jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {
        guiRun = true;
        if (radiusChk.isSelected()) {
            Store.radius = Integer.parseInt(radTxt.getText());
        }
        if (B2PChk.isSelected()) {
            Store.B2P = true;
        }
        if (bankChk.isSelected()) {
            Store.Banking = true;
        }
        this.dispose();
    }

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (localNpc.getSelectedItem() != null) {
            Store.npcNames.add((String) localNpc.getSelectedItem());
            localNpc.setSelectedItem(null);
        } else if (npcTxt.getText() != null) {

            Store.npcNames.add(npcTxt.getText());

        }
        npcList.setListData(Store.npcNames.toArray(new String[Store.npcNames.size()]));
    }

    private void addLootActionPerformed(java.awt.event.ActionEvent evt) {
        if (lootTxt.getText() != null) {
            Store.lootNames.add(lootTxt.getText());
            lootList.setListData(Store.lootNames.toArray(new String[Store.npcNames.size()]));
        }
    }

    private void addAlchActionPerformed(java.awt.event.ActionEvent evt) {
        if (toAlchTxt.getText() != null) {
            Store.alchNames.add((toAlchTxt.getText()));
            alchList.setListData(Store.alchNames.toArray(new String[Store.alchNames.size()]));
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        //load
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // save
    }

    private void alchChkActionPerformed(java.awt.event.ActionEvent evt) {
        alchList.setEnabled(true);

    }


    // Variables declaration - do not modify
    private javax.swing.JCheckBox B2PChk;
    private javax.swing.JButton addAlch;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addLoot;
    private javax.swing.JCheckBox alchChk;
    private javax.swing.JList alchList;
    private javax.swing.JCheckBox bankChk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox localNpc;
    private javax.swing.JList lootList;
    private javax.swing.JTextField lootTxt;
    private javax.swing.JList npcList;
    private javax.swing.JTextField npcTxt;
    private javax.swing.JTextField radTxt;
    private javax.swing.JCheckBox radiusChk;
    private javax.swing.JButton startBtn;
    private javax.swing.JTextField toAlchTxt;
    // End of variables declaration
}
